CU-86ctxw2uw - env example and add condition to firebase
vaionex/VBS pull request #33
Opened 2023-11-14 11:21 UTC by vaionexbusra

**Task**

[Link](https://app.clickup.com/t/86ctxw2uw)

**Implementation** 

Env.local filled with the name of the keys. 
Initialize firebase has added condition. (for firebase, storage and firestore.)

2023-11-15 09:57 UTC, mrf1freak requested changes

2023-11-15 09:57 UTC, mrf1freak commented on src/utils/stripe/index.js
>      throw error
If we fail to fetch any plans, we return placeholder plans

2023-11-16 00:19 UTC, paulsp94 reviewed
This should have been 2 PRs perhaps, one for stripe and on for firebase

2023-11-16 00:19 UTC, paulsp94 commented on src/app/api/stripe/checkout/route.js
> +      success_url: 'http://localhost:3000/pricing',
this is definitly wrong and will break in every deployment

2023-11-16 00:19 UTC, paulsp94 commented on src/components/Pricing/index.jsx
> +  // const [currentPlan, setCurrentPlan] = useState('')
remove this we dont want dead code

2023-11-16 00:19 UTC, paulsp94 commented on src/utils/stripe/index.js
> +// export const initiateSubscription = async (planProductId, errorHandle) => {
can we clean this up

2023-11-17 19:18 UTC, merged